version: "3.8"

services:
  research-to-startup-app:
    build: .
    container_name: research-to-startup-ai
    ports:
      - "8501:8501"
    environment:
      # Gemini API Configuration
      - GEMINI_API_KEY=${GEMINI_API_KEY:-demo-key-placeholder}
      - GEMINI_MODE=${GEMINI_MODE:-demo}

      # Tavily API Configuration
      - TAVILY_API_KEY=${TAVILY_API_KEY:-demo-key-placeholder}
      - TAVILY_MODE=${TAVILY_MODE:-demo}

      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

      # Application Settings
      - APP_TITLE=Research-to-Startup AI Agent Swarm
      - APP_ICON=🚀
      - APP_LAYOUT=wide

      # Agent Settings
      - AGENT_PROCESSING_DELAY=1
      - MAX_TEXT_LENGTH=10000

      # PDF Settings
      - MAX_PDF_PAGES=50

      # Output Settings
      - DEFAULT_OUTPUT_DIR=output
      - PITCH_DECK_FILENAME=pitch_deck.pdf
    volumes:
      # Mount output directory to persist generated files
      - ./output:/app/output
      # Mount data directory for investor data
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - research-ai-network

networks:
  research-ai-network:
    driver: bridge
# Optional: Add a reverse proxy for production deployment
# Uncomment the following section if you want to use nginx as reverse proxy
#
# services:
#   nginx:
#     image: nginx:alpine
#     container_name: research-ai-nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./ssl:/etc/nginx/ssl:ro
#     depends_on:
#       - research-to-startup-app
#     networks:
#       - research-ai-network
